In [26]:
# mencari datasets
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

file_directory = 'train.csv'

df = pd.read_csv(file_directory)

df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [27]:
# definisikan top features nya
top_features = [
    "OverallQual",
    "GrLivArea",
    "GarageCars",
    "GarageArea",
    "TotalBsmtSF",
    "1stFlrSF",
    "FullBath",
    "TotRmsAbvGrd",
    "YearBuilt",
    "YearRemodAdd",
    "GarageYrBlt",
    "MasVnrArea",
    "Fireplaces",
    "BsmtFinSF1",
    "LotFrontage",
    "WoodDeckSF"
]

# masukkan ke x dan y
x = df[top_features]
y = df.SalePrice

x.head()

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd,GarageYrBlt,MasVnrArea,Fireplaces,BsmtFinSF1,LotFrontage,WoodDeckSF
0,7,1710,2,548,856,856,2,8,2003,2003,2003.0,196.0,0,706,65.0,0
1,6,1262,2,460,1262,1262,2,6,1976,1976,1976.0,0.0,1,978,80.0,298
2,7,1786,2,608,920,920,2,6,2001,2002,2001.0,162.0,1,486,68.0,0
3,7,1717,3,642,756,961,1,7,1915,1970,1998.0,0.0,1,216,60.0,0
4,8,2198,3,836,1145,1145,2,9,2000,2000,2000.0,350.0,1,655,84.0,192

In [28]:
# memisahkan train test
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.2, random_state=1)
print("Variabel berhasil dipisahkan...")

Variabel berhasil dipisahkan...

In [29]:
# gunakan random forest dan buat 5 model untuk menguji
model_1 = RandomForestRegressor(
    n_estimators=50, 
    random_state=0
    )
model_2 = RandomForestRegressor(
    n_estimators=100, 
    min_samples_leaf=5, 
    random_state=0
    )
model_3 = RandomForestRegressor(
    n_estimators=100, 
    criterion='squared_error', 
    random_state=0
    )
model_4 = RandomForestRegressor(
    n_estimators=100,
    criterion='absolute_error', 
    random_state=0
    )
model_5 = RandomForestRegressor(
    n_estimators=200, 
    max_depth=7, 
    random_state=0
    )
model_6 = RandomForestRegressor(
    n_estimators=100,
    max_features=0.5,   # atau 'sqrt', 'log2', atau angka int
    random_state=0
)
model_7 = RandomForestRegressor(
    n_estimators=100,
    min_samples_split=10,
    random_state=0
)
model_8 = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    min_samples_leaf=3,
    random_state=0
)

models = [model_1, model_2, model_3, model_4, model_5, model_6, model_7, model_8]

In [30]:
# looping untuk mengetahui model mana yang bagus
# buat fungsi untuk mendapatkan score
def score_model(how_model, t_x=train_x, v_x=test_x, t_y=train_y, v_y=test_y):
    how_model.fit(t_x,t_y)
    predicts = how_model.predict(v_x)
    my_mae = mean_absolute_error(v_y, predicts)

    return my_mae

for i in range(0, len(models)):
    mae = score_model(models[i])
    print(f"Dengan model : %d \t\t MAE score : {mae:,.0f}" %(i+1))

Dengan model : 1 		 MAE score : 17,395
Dengan model : 2 		 MAE score : 17,901
Dengan model : 3 		 MAE score : 17,374
Dengan model : 4 		 MAE score : 17,924
Dengan model : 5 		 MAE score : 18,176
Dengan model : 6 		 MAE score : 17,434
Dengan model : 7 		 MAE score : 17,540
Dengan model : 8 		 MAE score : 17,987

In [31]:
best_model = model_3
best_model.fit(x, y)
print("successfully learned...")

successfully learned...

In [32]:
# masukkan ke dalam data test
dft = pd.read_csv('test.csv')

# ambil parameter yang diperlukan
x_evaluation = dft[top_features]

x_evaluation.head()

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd,GarageYrBlt,MasVnrArea,Fireplaces,BsmtFinSF1,LotFrontage,WoodDeckSF
0,5,896,1.0,730.0,882.0,896,1,5,1961,1961,1961.0,0.0,0,468.0,80.0,140
1,6,1329,1.0,312.0,1329.0,1329,1,6,1958,1958,1958.0,108.0,0,923.0,81.0,393
2,5,1629,2.0,482.0,928.0,928,2,6,1997,1998,1997.0,0.0,1,791.0,74.0,212
3,6,1604,2.0,470.0,926.0,926,2,7,1998,1998,1998.0,20.0,1,602.0,78.0,360
4,8,1280,2.0,506.0,1280.0,1280,2,5,1992,1992,1992.0,0.0,0,263.0,43.0,0

In [35]:
# mulai prediksi model
predicted = best_model.predict(x_evaluation)
print("Successfully predicted...")
print(predicted)

Successfully predicted...
[125813.41 155105.8  176666.94 ... 158121.05 106489.   236750.58]

In [38]:
# buat excel submission
submission = pd.DataFrame({
    'Id' : dft['Id'],
    'SalePrice' : predicted
})

submission.to_csv("submission.csv", index=False)
print(submission.head())

     Id  SalePrice
0  1461  125813.41
1  1462  155105.80
2  1463  176666.94
3  1464  185276.50
4  1465  199524.41