In [23]:
# import yang dibutuhkan terlebih dahulu
import pandas as pd
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# baca filenya
read_file = 'train.csv'
home_file = pd.read_csv(read_file)
# tes dengan membaca filenya

home_file.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [24]:
# liat apa saja kolom yang disediakan oleh data tersebut
home_file.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [25]:
# pisahkan hanya yang berguna untuk prediksi sale pricenya
top_features = [
    "OverallQual",
    "GrLivArea",
    "GarageCars",
    "GarageArea",
    "TotalBsmtSF",
    "1stFlrSF",
    "FullBath",
    "TotRmsAbvGrd",
    "YearBuilt",
    "YearRemodAdd",
    "GarageYrBlt",
    "MasVnrArea",
    "Fireplaces",
    "BsmtFinSF1",
    "LotFrontage",
    "WoodDeckSF"
]

x = home_file[top_features]

y = home_file.SalePrice

x.head()

,OverallQual,GrLivArea,GarageCars,GarageArea,TotalBsmtSF,1stFlrSF,FullBath,TotRmsAbvGrd,YearBuilt,YearRemodAdd,GarageYrBlt,MasVnrArea,Fireplaces,BsmtFinSF1,LotFrontage,WoodDeckSF
0,7,1710,2,548,856,856,2,8,2003,2003,2003.0,196.0,0,706,65.0,0
1,6,1262,2,460,1262,1262,2,6,1976,1976,1976.0,0.0,1,978,80.0,298
2,7,1786,2,608,920,920,2,6,2001,2002,2001.0,162.0,1,486,68.0,0
3,7,1717,3,642,756,961,1,7,1915,1970,1998.0,0.0,1,216,60.0,0
4,8,2198,3,836,1145,1145,2,9,2000,2000,2000.0,350.0,1,655,84.0,192

In [26]:
# pisahkan variabel train dan test dalam data itu sendiri
train_x, test_x, train_y, test_y = train_test_split(x, y, random_state=0)
print("Separating success...")

Separating success...

In [27]:
# buat model decision tree
house_model_price = DecisionTreeRegressor(random_state=1)
house_model_price.fit(train_x, train_y)

# prediksi hasil
house_saleprice_predict = house_model_price.predict(test_x)
print("Prediksi Berhasil...")

print(house_saleprice_predict)

Prediksi Berhasil...
[223000. 115000. 135000. 200000. 100000. 108480. 245000. 106500. 342643.
 116900. 196000. 135000. 239000. 142500. 155000. 155000. 236000.  80000.
 143500. 311500. 159000. 143000. 125000. 178000. 140000. 236500. 177000.
  75500. 337500. 133000. 141000. 185000. 143750. 281000. 369900. 189000.
 264132. 119500. 230000. 340000. 259500. 123000. 176485. 147000. 315000.
 153900. 116000. 147000. 149500.  64500. 342643. 145000. 145000.  55000.
 259000.  85500. 167500. 275000. 128900. 116500. 140000. 133700. 153337.
 129000. 215000. 127500. 158000. 205950. 134900. 155835. 180000. 113000.
  93500. 254000.  84000. 227000. 144000. 105500. 280000. 179900. 139000.
 125000. 109900. 156000. 185000. 204000.  58500. 202500. 176432. 133700.
 208900. 208900. 183200. 250000. 198900. 150000. 204000. 154000. 120500.
 149000. 311872. 219210. 143500. 148000.  73000. 299800. 144000. 141000.
 163990. 127000.  73000. 145000. 158000.  88000. 216000. 148500. 466500.
 129500. 137450. 252000. 139400. 216000. 136500. 207500. 213000. 224000.
 310000. 195400. 212000. 179900. 226000. 198900. 189000. 139000.  85500.
 213000. 113000. 187100.  96500. 178000. 147000. 147000. 200000. 156000.
 154000. 183200. 202500. 139000. 318061. 190000. 158000. 377426. 310000.
 133900. 236500. 260000. 129500. 236500.  84500. 168500. 120500. 157900.
 215200.  94750. 245000.  85000. 152000. 315750. 204000. 172400. 159000.
 151000. 162000. 176000. 119000. 124000. 139000. 272000. 128000. 152000.
 369900. 236000. 106500. 297000. 105000. 165000. 100000. 194500. 198900.
 131500. 156000. 144000. 203000. 135000. 110000. 156000.  86000. 151500.
 154000. 124900. 130000. 245500.  73000.  80000. 135000. 145000. 147500.
 337500. 275000.  58500. 155000. 286000.  93500. 116500. 360000. 200000.
 260000. 260000. 245000.  86000. 260000. 185750. 165000. 117500. 171750.
 280000. 340000. 200000. 125500. 176500.  93500. 178400.  88000. 140000.
 199900.  97500. 135000. 129000. 108000. 149500. 127000. 177000. 176500.
 231500. 164900. 174000. 197000. 195000. 154900. 204000. 168000. 252000.
  93500. 625000. 254000. 200000.  92000. 224000. 410000. 184750. 227000.
 167500. 124500. 137500. 326000. 395192. 305900.  60000. 167500. 318000.
 130000. 311500. 137000. 189000. 113000. 230000. 225000. 185000. 219500.
 110000. 137000. 326000. 145250. 159000. 194500. 210000. 113000. 236500.
 380000. 128000.  52500.  83000. 310000. 109900. 100000. 270000. 212900.
 202500. 132500. 151000.  83500. 129000. 179665. 165000. 140000. 163000.
  88000. 121500. 189000. 212000.  55993. 164500. 140000. 127500. 133000.
 141000. 305900. 121600. 185500. 140000. 115000. 236500. 115000. 260000.
 138887. 237000. 123000. 377426. 207500. 141000. 117500. 232000. 154000.
 181134. 220000. 142000. 124500. 178000. 189000. 126500. 360000. 153500.
 140000. 219500. 143000. 145250. 145000.  55993. 108000. 139000. 193000.
 475000. 129000. 105500. 162000. 326000. 290000. 225000. 275000. 257500.
 556581. 173000. 260000. 227000.  93500.]

In [28]:
# mengetahui berapa errornya
rmse = root_mean_squared_error(test_y, house_saleprice_predict)
print(f"Nilai rmse nya adalah : {rmse:,.0f}")

Nilai rmse nya adalah : 45,354

In [29]:
# mendapatkan rmse nya
def get_rmse(max_leaf_nodes, x_train, x_test, y_train, y_test):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=42)
    model.fit(x_train, y_train)
    predict_result = model.predict(x_test)
    rmse = root_mean_squared_error(y_test, predict_result)

    return rmse

In [30]:
# menggunakan max leaf sebagai penilaian
for max_leaf_nodes in [5, 25, 50, 100, 250, 500, 1000]:
    my_rmse = get_rmse(max_leaf_nodes, train_x, test_x, train_y, test_y)
    print(f"Max Leaf Nodes : {max_leaf_nodes} \t\t RMSE : {my_rmse:,.0f}")

best_max_leaf_nodes = 100

Max Leaf Nodes : 5 		 RMSE : 48,308
Max Leaf Nodes : 25 		 RMSE : 45,963
Max Leaf Nodes : 50 		 RMSE : 43,526
Max Leaf Nodes : 100 		 RMSE : 42,639
Max Leaf Nodes : 250 		 RMSE : 44,588
Max Leaf Nodes : 500 		 RMSE : 44,793
Max Leaf Nodes : 1000 		 RMSE : 44,908

In [31]:
# mencoba menggunakan random forest regressor
model_regressor = RandomForestRegressor(random_state=1)
model_regressor.fit(train_x, train_y)

predict_with_random_forest = model_regressor.predict(test_x)

# hitung rmse nya
rmse_random_forest = root_mean_squared_error(test_y, predict_with_random_forest)

print(f"Hasil rmse dari random forest regressor adalah : {rmse_random_forest:,.0f}")
# karena rendah maka memakai random forest regressor

Hasil rmse dari random forest regressor adalah : 31,293

In [32]:
# memulai prediksi dengan data test
test_data = 'test.csv'
read_test_data = pd.read_csv(test_data)

read_test_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [33]:
# ambil data features dari data test
x_compe_data = read_test_data[top_features]
# mulai prediksi
final_predict = model_regressor.predict(x_compe_data)
print(f"Rata rata hasil prediksi adalah : {final_predict.mean():,.3f}")
print("Prediksi berhasil....")

Rata rata hasil prediksi adalah : 178,962.905
Prediksi berhasil....

In [34]:
# masukkan ke dalam file submission
# Ganti 'id' di bawah sesuai nama kolom asli di dataset kamu (misal: 'Id', 'ID', 'user_id')
submission = pd.DataFrame({
    'Id': read_test_data['Id'],
    'SalePrice': final_predict
})

submission.to_csv("submission.csv", index=False)
print(submission.head())

     Id  SalePrice
0  1461  121274.73
1  1462  147713.40
2  1463  180286.45
3  1464  190424.00
4  1465  206165.24