In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

# load data dengan pandas
file_directory = 'melb_data_house.csv'
read_data = pd.read_csv(file_directory)

read_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [ ]:
# identifikasi variabel 
read_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='str')

In [6]:
data_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']
# masukkan ke dalam x
x = read_data[data_features]

# definisikan y dengan harga
y = read_data.Price

x.head()

   Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2       1.0     202.0   -37.7996    144.9984
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
3      3       2.0      94.0   -37.7969    144.9969
4      4       1.0     120.0   -37.8072    144.9941

In [16]:
# pisahkan dengan train dan test
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

# buat modelnya
housing_model = DecisionTreeRegressor()
housing_model.fit(x_train, y_train)

# lakukan prediksi dengan y test
house_price_prediction = housing_model.predict(x_test)
# print(house_price_prediction)
# print("Perbandingan dengan nilai asli")
# print(y_test.head(10))

# hitung selisih dari prediksi dengan nilai asli
difference = y_test - house_price_prediction

comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": house_price_prediction,
    "Sum" : difference
})
print(comparison.head(10))

mae_values = mean_absolute_error(y_test, house_price_prediction)

print(f"Mean Absolute Error: {mae_values}")

          Actual  Predicted       Sum
8505   2165000.0  1325000.0  840000.0
5523    815000.0   950000.0 -135000.0
12852   610000.0   571000.0   39000.0
4818   1245000.0  1220000.0   25000.0
12812  1160000.0  1040000.0  120000.0
2153   1250000.0  1225000.0   25000.0
9903    715000.0   783000.0  -68000.0
5105    812000.0   928000.0 -116000.0
6107    750500.0   668000.0   82500.0
8876    610000.0   596000.0   14000.0
Mean Absolute Error: 248986.4854197349